# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- develop

pool:
  vmImage: ubuntu-latest

steps:
- task: DotNetCoreCLI@2
  displayName: 'Dotnet test'
  inputs:
    command: test
    projects: '**/Test'
- script: |
   git checkout develop
   git remote add heroku https://heroku:$(API_KEY)@git.heroku.com/staging-movie-platform-sep6.git
   git push heroku develop:main
  displayName: 'Push To Heroku'
- task: robmburke.ado-discord-webhook.custom-build-release-task.ado-discord-webhook@1
  displayName: 'Release message'
  inputs:
    channelId: 968599999627796550
    webhookKey: 'bZFWvzNkjIr0EYlabrdy__V_0l0SxXxZTWRFKxAEzYfnYANhnb_H6IjlLKChWPTz5PSx'
    name: DevOps
    avatar: 'https://www.google.com/imgres?imgurl=https%3A%2F%2Fp2zk82o7hr3yb6ge7gzxx4ki-wpengine.netdna-ssl.com%2Fwp-content%2Fuploads%2FAzure-DevOps-3.png&imgrefurl=https%3A%2F%2Fwww.parkmycloud.com%2Fblog%2Fazure-devops%2F&tbnid=jx9OGJjxwveaAM&vet=12ahUKEwi-qPC6wLL3AhVM9aQKHbraAfoQMygAegUIARDZAQ..i&docid=gNW78kdqZ3gaNM&w=800&h=500&q=azure%20devops%20logo&ved=2ahUKEwi-qPC6wLL3AhVM9aQKHbraAfoQMygAegUIARDZAQ'
    messageType: content
    content: 'A new build have been released to Heroku for **Staging**! Change(s): "**$(Build.SourceVersionMessage)**" Version: "**$(Build.BuildNumber)**"'
